# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-11 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190522_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='tittle',
        ),
    ]
